'use client';

import { useLanguageCtx } from '@/contexts/LanguageCtx';

// Simple translation mapping for common demo texts
const translations: Record<string, Record<string, string>> = {
  es: {
    // Common UI elements
    'Submit': 'Enviar',
    'Submit Assessment': 'Enviar Evaluación',
    'Score applicant': 'Evaluar solicitante',
    'Generate Report': 'Generar Reporte',
    'View Details': 'Ver Detalles',
    'Export Data': 'Exportar Datos',
    'Back': 'Volver',
    'Loading...': 'Cargando...',
    'Reset': 'Restablecer',
    'Clear': 'Limpiar',
    'Save': 'Guardar',
    'Cancel': 'Cancelar',
    'Close': 'Cerrar',
    'Next': 'Siguiente',
    'Previous': 'Anterior',
    
    // Credit Risk Demo
    'Credit Risk Assessment': 'Evaluación de Riesgo Crediticio',
    'Credit Risk Prediction Demo': 'Demo de Predicción de Riesgo Crediticio',
    'Assessment': 'Evaluación',
    'Name': 'Nombre',
    'Age': 'Edad',
    'Income': 'Ingresos',
    'Annual Income ($)': 'Ingresos Anuales ($)',
    'Loan Amount': 'Monto del Préstamo',
    'Loan Amount ($)': 'Monto del Préstamo ($)',
    'Credit Score': 'Puntaje Crediticio',
    'Credit History': 'Historial Crediticio',
    'Existing Loans': 'Préstamos Existentes',
    'Employment': 'Empleo',
    'Employment Status': 'Estado de Empleo',
    'Employed': 'Empleado',
    'Self-Employed': 'Trabajador Independiente',
    'Unemployed': 'Desempleado',
    'Predict Risk': 'Predecir Riesgo',
    'Predicted Risk': 'Riesgo Predicho',
    'High Risk': 'Alto Riesgo',
    'Low Risk': 'Bajo Riesgo',
    'Medium Risk': 'Riesgo Medio',
    'Risk Score': 'Puntuación de Riesgo',
    'Risk Analysis': 'Análisis de Riesgo',
    'Repay Prob': 'Prob. Pago',
    'Category': 'Categoría',
    'Expected loss (LGD 40%)': 'Pérdida esperada (LGD 40%)',
    'Top drivers (contributions)': 'Principales factores (contribuciones)',
    'Or pick a sample (prefills form)': 'O elige una muestra (completa el formulario)',
    'Enter values and click "Score applicant".': 'Ingresa valores y haz clic en "Evaluar solicitante".',
    
    // Model metrics
    'Model discrimination': 'Discriminación del modelo',
    'Positive predictive value': 'Valor predictivo positivo',
    'Sensitivity': 'Sensibilidad',
    'Expected loss reduction': 'Reducción de pérdida esperada',
    
    // Risk levels and decisions
    'Low (<20%)': 'Bajo (<20%)',
    'Medium (20-50%)': 'Medio (20-50%)',
    'High (>=50%)': 'Alto (>=50%)',
    'Auto-approve': 'Auto-aprobar',
    'Manual review': 'Revisión manual',
    'Reject': 'Rechazar',
    'score<0.2 & DTI<35%': 'puntuación<0.2 & DTI<35%',
    '0.2<=score<0.5 or DTI 35-50%': '0.2<=puntuación<0.5 o DTI 35-50%',
    'score>=0.5 or severe delinquency': 'puntuación>=0.5 o morosidad severa',
    'Risk Distribution': 'Distribución de Riesgo',
    'Approval Policies': 'Políticas de Aprobación',
    'Policy levers': 'Palancas de políticas',
    
    // Product Recommendation Demo
    'View similar': 'Ver similares',
    'Add to cart': 'Agregar al carrito',
    'Promote Variant': 'Promover Variante',
    'Recent Activity': 'Actividad Reciente',
    'Personalized for': 'Personalizado para',
    'User Context': 'Contexto del Usuario',
    'Top Recommendations': 'Principales Recomendaciones',
    'Offline Metrics': 'Métricas Offline',
    'Online Metrics': 'Métricas Online',
    'Similar Items (Content-Based)': 'Artículos Similares (Basado en Contenido)',
    'Frequently Bought Together': 'Frecuentemente Comprados Juntos',
    'A/B Test Results': 'Resultados de Prueba A/B',
    'Product Recommendation System': 'Sistema de Recomendación de Productos',
    'Hybrid (Collaborative + Content) Recommendations with Evaluation and A/B Testing': 'Recomendaciones Híbridas (Colaborativas + Contenido) con Evaluación y Pruebas A/B',
    
    // Email Automation Demo
    'Email Automation Platform': 'Plataforma de Automatización de Email',
    'Campaign Overview': 'Resumen de Campaña',
    'Template Library': 'Biblioteca de Plantillas',
    'Analytics Dashboard': 'Panel de Análisis',
    'Campaigns': 'Campañas',
    'Templates': 'Plantillas',
    'Analytics': 'Análisis',
    'Status': 'Estado',
    'Sent': 'Enviado',
    'Open Rate': 'Tasa de Apertura',
    'Click Rate': 'Tasa de Clics',
    'Active': 'Activo',
    'Scheduled': 'Programado',
    'Completed': 'Completado',
    'Paused': 'Pausado',
    'Welcome Series': 'Serie de Bienvenida',
    'Product Launch': 'Lanzamiento de Producto',
    'Abandoned Cart': 'Carrito Abandonado',
    'Weekly Newsletter': 'Boletín Semanal',
    
    // Sales Analytics Demo  
    'Sales Analytics Dashboard': 'Panel de Análisis de Ventas',
    'Revenue': 'Ingresos',
    'Revenue Growth': 'Crecimiento de Ingresos',
    'Customer Retention': 'Retención de Clientes',
    'Conversion Rate': 'Tasa de Conversión',
    'Performance Metrics': 'Métricas de Rendimiento',
    'Total Revenue': 'Ingresos Totales',
    'New Customers': 'Nuevos Clientes',
    'Monthly Growth': 'Crecimiento Mensual',
    'Pipeline Value': 'Valor del Pipeline',
    
    // Marketing Campaign Demo
    'Marketing Campaign Analytics': 'Análisis de Campañas de Marketing',
    'Campaign Performance': 'Rendimiento de Campañas',
    'ROI Analysis': 'Análisis de ROI',
    'Budget': 'Presupuesto',
    'Spent': 'Gastado',
    'ROI': 'ROI',
    'Conversions': 'Conversiones',
    'Channel': 'Canal',
    'Email': 'Correo Electrónico',
    'Social Media': 'Redes Sociales',
    'Paid Search': 'Búsqueda Pagada',
    
    // Customer Scoring Demo
    'Customer Scoring System': 'Sistema de Puntuación de Clientes',
    'Customer Score': 'Puntuación del Cliente',
    'Churn Risk': 'Riesgo de Abandono',
    'Lifetime Value': 'Valor de por Vida',
    'Engagement Score': 'Puntuación de Compromiso',
    
    // Product Recommendation Demo
    'Product Recommendation Engine': 'Motor de Recomendación de Productos',
    'Recommended Products': 'Productos Recomendados',
    'Similar Items': 'Artículos Similares',
    'Trending Now': 'Tendencias Actuales',
    
    // Trading Bot Demo
    'Trading Bot Interface': 'Interfaz del Bot de Trading',
    'Portfolio Value': 'Valor del Portafolio',
    'Daily P&L': 'P&L Diario',
    'Win Rate': 'Tasa de Ganancia',
    'Risk Level': 'Nivel de Riesgo',
    'Buy': 'Comprar',
    'Sell': 'Vender',
    'Hold': 'Mantener',
    
    // UI Showcase Demo
    'UI Design Showcase': 'Showcase de Diseño UI',
    'Product Dashboard': 'Panel de Productos',
    'Users': 'Usuarios',
    'Orders': 'Pedidos',
    'Conversion': 'Conversión',
    
    // General terms
    'Dashboard': 'Panel',
    'Overview': 'Resumen',
    'Details': 'Detalles',
    'Settings': 'Configuración',
    'Profile': 'Perfil',
    'Search': 'Buscar',
    'Filter': 'Filtrar',
    'Sort': 'Ordenar',
    'Date Range': 'Rango de Fechas',
    'Export': 'Exportar',
    'Import': 'Importar',
    'Refresh': 'Actualizar',
    'Edit': 'Editar',
    'Delete': 'Eliminar',
    'Add': 'Agregar',
    'Create': 'Crear',
    'Update': 'Actualizar',
    'Remove': 'Eliminar',
    'Select': 'Seleccionar',
    'Choose': 'Elegir',
    'Upload': 'Subir',
    'Download': 'Descargar',
    'Print': 'Imprimir',
    'Share': 'Compartir',
    'Copy': 'Copiar',
    'Paste': 'Pegar',
    'Cut': 'Cortar',
    'Undo': 'Deshacer',
    'Redo': 'Rehacer',
    'Help': 'Ayuda',
    'About': 'Acerca de',
    'Contact': 'Contacto',
    'Support': 'Soporte',
    'Feedback': 'Comentarios',
    'Report': 'Reporte',
    'Bug': 'Error',
    'Feature': 'Característica',
    'Request': 'Solicitud',
    'Issue': 'Problema',
    'Fix': 'Arreglar',
    'Error': 'Error',
    'Warning': 'Advertencia',
    'Info': 'Información',
    'Success': 'Éxito',
    'Failed': 'Falló',
    'Pending': 'Pendiente',
    'Processing': 'Procesando',
    'Complete': 'Completo',
    'Incomplete': 'Incompleto',
    'Yes': 'Sí',
    'No': 'No',
    'True': 'Verdadero',
    'False': 'Falso',
    'On': 'Activado',
    'Off': 'Desactivado',
    'Enabled': 'Habilitado',
    'Disabled': 'Deshabilitado',
  },
  
  // French translations
  fr: {
    // Common UI elements
    'Submit': 'Soumettre',
    'Submit Assessment': 'Soumettre l\'évaluation',
    'Score applicant': 'Évaluer le candidat',
    'Generate Report': 'Générer un rapport',
    'View Details': 'Voir les détails',
    'Export Data': 'Exporter les données',
    'Back': 'Retour',
    'Loading...': 'Chargement...',
    'Reset': 'Réinitialiser',
    'Clear': 'Effacer',
    'Save': 'Sauvegarder',
    'Cancel': 'Annuler',
    'Close': 'Fermer',
    'Next': 'Suivant',
    'Previous': 'Précédent',
    
    // Credit Risk Demo
    'Credit Risk Assessment': 'Évaluation du risque de crédit',
    'Credit Risk Prediction Demo': 'Démo de prédiction du risque de crédit',
    'Assessment': 'Évaluation',
    'Name': 'Nom',
    'Age': 'Âge',
    'Income': 'Revenus',
    'Annual Income ($)': 'Revenus annuels ($)',
    'Loan Amount': 'Montant du prêt',
    'Loan Amount ($)': 'Montant du prêt ($)',
    'Credit Score': 'Score de crédit',
    'Credit History': 'Historique de crédit',
    'Existing Loans': 'Prêts existants',
    'Employment': 'Emploi',
    'Employment Status': 'Statut d\'emploi',
    'Employed': 'Employé',
    'Self-Employed': 'Travailleur autonome',
    'Unemployed': 'Chômeur',
    'Predict Risk': 'Prédire le risque',
    'Predicted Risk': 'Risque prédit',
    'High Risk': 'Risque élevé',
    'Low Risk': 'Faible risque',
    'Medium Risk': 'Risque moyen',
    'Risk Score': 'Score de risque',
    'Risk Analysis': 'Analyse des risques',
    'Repay Prob': 'Prob. remboursement',
    'Category': 'Catégorie',
    'Expected loss (LGD 40%)': 'Perte attendue (LGD 40%)',
    'Top drivers (contributions)': 'Principaux facteurs (contributions)',
    'Or pick a sample (prefills form)': 'Ou choisir un échantillon (pré-remplit le formulaire)',
    'Enter values and click "Score applicant".': 'Saisissez les valeurs et cliquez sur "Évaluer le candidat".',
    
    // Model metrics
    'Model discrimination': 'Discrimination du modèle',
    'Positive predictive value': 'Valeur prédictive positive',
    'Sensitivity': 'Sensibilité',
    'Expected loss reduction': 'Réduction de perte attendue',
    
    // Risk levels and decisions
    'Low (<20%)': 'Faible (<20%)',
    'Medium (20-50%)': 'Moyen (20-50%)',
    'High (>=50%)': 'Élevé (>=50%)',
    'Auto-approve': 'Approbation automatique',
    'Manual review': 'Examen manuel',
    'Reject': 'Rejeter',
    'score<0.2 & DTI<35%': 'score<0.2 & DTI<35%',
    '0.2<=score<0.5 or DTI 35-50%': '0.2<=score<0.5 ou DTI 35-50%',
    'score>=0.5 or severe delinquency': 'score>=0.5 ou délinquance sévère',
    'Risk Distribution': 'Distribution des risques',
    'Approval Policies': 'Politiques d\'approbation',
    'Policy levers': 'Leviers de politique',
    
    // Email Automation Demo
    'Email Automation Platform': 'Plateforme d\'automatisation email',
    'Campaign Overview': 'Aperçu de la campagne',
    'Template Library': 'Bibliothèque de modèles',
    'Analytics Dashboard': 'Tableau de bord analytique',
    'Campaigns': 'Campagnes',
    'Templates': 'Modèles',
    'Analytics': 'Analytique',
    'Status': 'Statut',
    'Sent': 'Envoyé',
    'Open Rate': 'Taux d\'ouverture',
    'Click Rate': 'Taux de clic',
    'Active': 'Actif',
    'Scheduled': 'Programmé',
    'Completed': 'Terminé',
    'Paused': 'En pause',
    'Welcome Series': 'Série de bienvenue',
    'Product Launch': 'Lancement de produit',
    'Abandoned Cart': 'Panier abandonné',
    'Weekly Newsletter': 'Newsletter hebdomadaire',
    'Modern Welcome': 'Bienvenue moderne',
    'Product Showcase': 'Vitrine de produits',
    'Minimal Newsletter': 'Newsletter minimaliste',
    'Flash Sale': 'Vente flash',
    'Onboarding': 'Intégration',
    'Marketing': 'Marketing',
    'Content': 'Contenu',
    'Promotional': 'Promotionnel',
    
    // Product Recommendation Demo
    'View similar': 'Voir similaires',
    'Add to cart': 'Ajouter au panier',
    'Promote Variant': 'Promouvoir la variante',
    'Recent Activity': 'Activité récente',
    'Personalized for': 'Personnalisé pour',
    'User Context': 'Contexte utilisateur',
    'Top Recommendations': 'Principales recommandations',
    'Offline Metrics': 'Métriques hors ligne',
    'Online Metrics': 'Métriques en ligne',
    'Similar Items (Content-Based)': 'Articles similaires (basé sur le contenu)',
    'Frequently Bought Together': 'Fréquemment achetés ensemble',
    'A/B Test Results': 'Résultats des tests A/B',
    'Product Recommendation System': 'Système de recommandation de produits',
    'Hybrid (Collaborative + Content) Recommendations with Evaluation and A/B Testing': 'Recommandations hybrides (collaboratives + contenu) avec évaluation et tests A/B',
    
    // General terms
    'Dashboard': 'Tableau de bord',
    'Overview': 'Aperçu',
    'Details': 'Détails',
    'Settings': 'Paramètres',
    'Profile': 'Profil',
    'Search': 'Rechercher',
    'Filter': 'Filtrer',
    'Sort': 'Trier',
    'Date Range': 'Plage de dates',
    'Export': 'Exporter',
    'Import': 'Importer',
    'Refresh': 'Actualiser',
    'Edit': 'Modifier',
    'Delete': 'Supprimer',
    'Add': 'Ajouter',
    'Create': 'Créer',
    'Update': 'Mettre à jour',
    'Remove': 'Supprimer',
    'Select': 'Sélectionner',
    'Choose': 'Choisir',
    'Upload': 'Télécharger',
    'Download': 'Télécharger',
    'Print': 'Imprimer',
    'Share': 'Partager',
    'Copy': 'Copier',
    'Paste': 'Coller',
    'Cut': 'Couper',
    'Undo': 'Annuler',
    'Redo': 'Rétablir',
    'Help': 'Aide',
    'About': 'À propos',
    'Contact': 'Contact',
    'Support': 'Support',
    'Feedback': 'Commentaires',
    'Report': 'Rapport',
    'Bug': 'Bug',
    'Feature': 'Fonctionnalité',
    'Request': 'Demande',
    'Issue': 'Problème',
    'Fix': 'Corriger',
    'Error': 'Erreur',
    'Warning': 'Avertissement',
    'Info': 'Information',
    'Success': 'Succès',
    'Failed': 'Échec',
    'Pending': 'En attente',
    'Processing': 'Traitement en cours',
    'Complete': 'Terminé',
    'Incomplete': 'Incomplet',
    'Yes': 'Oui',
    'No': 'Non',
    'True': 'Vrai',
    'False': 'Faux',
    'On': 'Activé',
    'Off': 'Désactivé',
    'Enabled': 'Activé',
    'Disabled': 'Désactivé',
  },
  
  // German translations
  de: {
    // Common UI elements
    'Submit': 'Einreichen',
    'Submit Assessment': 'Bewertung einreichen',
    'Score applicant': 'Bewerber bewerten',
    'Generate Report': 'Bericht generieren',
    'View Details': 'Details anzeigen',
    'Export Data': 'Daten exportieren',
    'Back': 'Zurück',
    'Loading...': 'Laden...',
    'Reset': 'Zurücksetzen',
    'Clear': 'Löschen',
    'Save': 'Speichern',
    'Cancel': 'Abbrechen',
    'Close': 'Schließen',
    'Next': 'Weiter',
    'Previous': 'Zurück',
    
    // Credit Risk Demo
    'Credit Risk Assessment': 'Kreditrisikobewertung',
    'Credit Risk Prediction Demo': 'Kreditrisiko-Vorhersage Demo',
    'Assessment': 'Bewertung',
    'Name': 'Name',
    'Age': 'Alter',
    'Income': 'Einkommen',
    'Annual Income ($)': 'Jahreseinkommen ($)',
    'Loan Amount': 'Darlehensbetrag',
    'Loan Amount ($)': 'Darlehensbetrag ($)',
    'Credit Score': 'Kredit-Score',
    'Credit History': 'Kreditgeschichte',
    'Existing Loans': 'Bestehende Darlehen',
    'Employment': 'Beschäftigung',
    'Employment Status': 'Beschäftigungsstatus',
    'Employed': 'Angestellt',
    'Self-Employed': 'Selbständig',
    'Unemployed': 'Arbeitslos',
    'Predict Risk': 'Risiko vorhersagen',
    'Predicted Risk': 'Vorhergesagtes Risiko',
    'High Risk': 'Hohes Risiko',
    'Low Risk': 'Geringes Risiko',
    'Medium Risk': 'Mittleres Risiko',
    'Risk Score': 'Risiko-Score',
    'Risk Analysis': 'Risikoanalyse',
    'Repay Prob': 'Rückzahlungswahrsch.',
    'Category': 'Kategorie',
    'Expected loss (LGD 40%)': 'Erwarteter Verlust (LGD 40%)',
    'Top drivers (contributions)': 'Haupttreiber (Beiträge)',
    'Or pick a sample (prefills form)': 'Oder wählen Sie ein Beispiel (füllt Formular vor)',
    'Enter values and click "Score applicant".': 'Geben Sie Werte ein und klicken Sie auf "Bewerber bewerten".',
    
    // Model metrics
    'Model discrimination': 'Modell-Diskriminierung',
    'Positive predictive value': 'Positiver Vorhersagewert',
    'Sensitivity': 'Sensitivität',
    'Expected loss reduction': 'Erwartete Verlustreduzierung',
    
    // Risk levels and decisions
    'Low (<20%)': 'Niedrig (<20%)',
    'Medium (20-50%)': 'Mittel (20-50%)',
    'High (>=50%)': 'Hoch (>=50%)',
    'Auto-approve': 'Automatisch genehmigen',
    'Manual review': 'Manuelle Überprüfung',
    'Reject': 'Ablehnen',
    'score<0.2 & DTI<35%': 'Score<0.2 & DTI<35%',
    '0.2<=score<0.5 or DTI 35-50%': '0.2<=Score<0.5 oder DTI 35-50%',
    'score>=0.5 or severe delinquency': 'Score>=0.5 oder schwere Zahlungsverzögerung',
    'Risk Distribution': 'Risikoverteilung',
    'Approval Policies': 'Genehmigungsrichtlinien',
    'Policy levers': 'Politik-Hebel',
    
    // Email Automation Demo
    'Email Automation Platform': 'E-Mail-Automatisierungsplattform',
    'Campaign Overview': 'Kampagnenübersicht',
    'Template Library': 'Vorlagenbibliothek',
    'Analytics Dashboard': 'Analytics-Dashboard',
    'Campaigns': 'Kampagnen',
    'Templates': 'Vorlagen',
    'Analytics': 'Analytics',
    'Status': 'Status',
    'Sent': 'Gesendet',
    'Open Rate': 'Öffnungsrate',
    'Click Rate': 'Klickrate',
    'Active': 'Aktiv',
    'Scheduled': 'Geplant',
    'Completed': 'Abgeschlossen',
    'Paused': 'Pausiert',
    'Welcome Series': 'Willkommensserie',
    'Product Launch': 'Produkteinführung',
    'Abandoned Cart': 'Verlassener Warenkorb',
    'Weekly Newsletter': 'Wöchentlicher Newsletter',
    'Modern Welcome': 'Modernes Willkommen',
    'Product Showcase': 'Produktpräsentation',
    'Minimal Newsletter': 'Minimalistischer Newsletter',
    'Flash Sale': 'Blitzverkauf',
    'Onboarding': 'Onboarding',
    'Marketing': 'Marketing',
    'Content': 'Inhalt',
    'Promotional': 'Werbung',
    
    // Product Recommendation Demo
    'View similar': 'Ähnliche anzeigen',
    'Add to cart': 'In den Warenkorb',
    'Promote Variant': 'Variante bewerben',
    'Recent Activity': 'Letzte Aktivität',
    'Personalized for': 'Personalisiert für',
    'User Context': 'Benutzerkontext',
    'Top Recommendations': 'Top-Empfehlungen',
    'Offline Metrics': 'Offline-Metriken',
    'Online Metrics': 'Online-Metriken',
    'Similar Items (Content-Based)': 'Ähnliche Artikel (inhaltsbasiert)',
    'Frequently Bought Together': 'Häufig zusammen gekauft',
    'A/B Test Results': 'A/B-Test-Ergebnisse',
    'Product Recommendation System': 'Produktempfehlungssystem',
    'Hybrid (Collaborative + Content) Recommendations with Evaluation and A/B Testing': 'Hybride (kollaborative + inhaltliche) Empfehlungen mit Bewertung und A/B-Tests',
    
    // General terms
    'Dashboard': 'Dashboard',
    'Overview': 'Übersicht',
    'Details': 'Details',
    'Settings': 'Einstellungen',
    'Profile': 'Profil',
    'Search': 'Suchen',
    'Filter': 'Filter',
    'Sort': 'Sortieren',
    'Date Range': 'Datumsbereich',
    'Export': 'Exportieren',
    'Import': 'Importieren',
    'Refresh': 'Aktualisieren',
    'Edit': 'Bearbeiten',
    'Delete': 'Löschen',
    'Add': 'Hinzufügen',
    'Create': 'Erstellen',
    'Update': 'Aktualisieren',
    'Remove': 'Entfernen',
    'Select': 'Auswählen',
    'Choose': 'Wählen',
    'Upload': 'Hochladen',
    'Download': 'Herunterladen',
    'Print': 'Drucken',
    'Share': 'Teilen',
    'Copy': 'Kopieren',
    'Paste': 'Einfügen',
    'Cut': 'Ausschneiden',
    'Undo': 'Rückgängig',
    'Redo': 'Wiederholen',
    'Help': 'Hilfe',
    'About': 'Über',
    'Contact': 'Kontakt',
    'Support': 'Support',
    'Feedback': 'Feedback',
    'Report': 'Bericht',
    'Bug': 'Fehler',
    'Feature': 'Feature',
    'Request': 'Anfrage',
    'Issue': 'Problem',
    'Fix': 'Reparieren',
    'Error': 'Fehler',
    'Warning': 'Warnung',
    'Info': 'Info',
    'Success': 'Erfolg',
    'Failed': 'Fehlgeschlagen',
    'Pending': 'Ausstehend',
    'Processing': 'Verarbeitung',
    'Complete': 'Vollständig',
    'Incomplete': 'Unvollständig',
    'Yes': 'Ja',
    'No': 'Nein',
    'True': 'Wahr',
    'False': 'Falsch',
    'On': 'An',
    'Off': 'Aus',
    'Enabled': 'Aktiviert',
    'Disabled': 'Deaktiviert',
  },
  
  // Polish translations
  pl: {
    // Common UI elements
    'Submit': 'Wyślij',
    'Submit Assessment': 'Wyślij ocenę',
    'Score applicant': 'Oceń wnioskodawcę',
    'Generate Report': 'Wygeneruj raport',
    'View Details': 'Zobacz szczegóły',
    'Export Data': 'Eksportuj dane',
    'Back': 'Wstecz',
    'Loading...': 'Ładowanie...',
    'Reset': 'Resetuj',
    'Clear': 'Wyczyść',
    'Save': 'Zapisz',
    'Cancel': 'Anuluj',
    'Close': 'Zamknij',
    'Next': 'Dalej',
    'Previous': 'Poprzedni',
    
    // Credit Risk Demo
    'Credit Risk Assessment': 'Ocena ryzyka kredytowego',
    'Credit Risk Prediction Demo': 'Demo przewidywania ryzyka kredytowego',
    'Assessment': 'Ocena',
    'Name': 'Imię',
    'Age': 'Wiek',
    'Income': 'Dochód',
    'Annual Income ($)': 'Roczny dochód ($)',
    'Loan Amount': 'Kwota pożyczki',
    'Loan Amount ($)': 'Kwota pożyczki ($)',
    'Credit Score': 'Ocena kredytowa',
    'Credit History': 'Historia kredytowa',
    'Existing Loans': 'Istniejące pożyczki',
    'Employment': 'Zatrudnienie',
    'Employment Status': 'Status zatrudnienia',
    'Employed': 'Zatrudniony',
    'Self-Employed': 'Samozatrudniony',
    'Unemployed': 'Bezrobotny',
    'Predict Risk': 'Przewiduj ryzyko',
    'Predicted Risk': 'Przewidziane ryzyko',
    'High Risk': 'Wysokie ryzyko',
    'Low Risk': 'Niskie ryzyko',
    'Medium Risk': 'Średnie ryzyko',
    'Risk Score': 'Wynik ryzyka',
    'Risk Analysis': 'Analiza ryzyka',
    'Repay Prob': 'Prawdop. spłaty',
    'Category': 'Kategoria',
    'Expected loss (LGD 40%)': 'Oczekiwana strata (LGD 40%)',
    'Top drivers (contributions)': 'Główne czynniki (wkłady)',
    'Or pick a sample (prefills form)': 'Lub wybierz przykład (wypełnia formularz)',
    'Enter values and click "Score applicant".': 'Wprowadź wartości i kliknij "Oceń wnioskodawcę".',
    
    // Model metrics
    'Model discrimination': 'Dyskryminacja modelu',
    'Positive predictive value': 'Dodatnia wartość predykcyjna',
    'Sensitivity': 'Czułość',
    'Expected loss reduction': 'Oczekiwana redukcja strat',
    
    // Risk levels and decisions
    'Low (<20%)': 'Niskie (<20%)',
    'Medium (20-50%)': 'Średnie (20-50%)',
    'High (>=50%)': 'Wysokie (>=50%)',
    'Auto-approve': 'Auto-zatwierdzenie',
    'Manual review': 'Przegląd ręczny',
    'Reject': 'Odrzuć',
    'score<0.2 & DTI<35%': 'wynik<0.2 & DTI<35%',
    '0.2<=score<0.5 or DTI 35-50%': '0.2<=wynik<0.5 lub DTI 35-50%',
    'score>=0.5 or severe delinquency': 'wynik>=0.5 lub poważne zaległości',
    'Risk Distribution': 'Rozkład ryzyka',
    'Approval Policies': 'Polityki zatwierdzania',
    'Policy levers': 'Dźwignie polityczne',
    
    // Email Automation Demo
    'Email Automation Platform': 'Platforma automatyzacji email',
    'Campaign Overview': 'Przegląd kampanii',
    'Template Library': 'Biblioteka szablonów',
    'Analytics Dashboard': 'Panel analityczny',
    'Campaigns': 'Kampanie',
    'Templates': 'Szablony',
    'Analytics': 'Analityka',
    'Status': 'Status',
    'Sent': 'Wysłano',
    'Open Rate': 'Wskaźnik otwarć',
    'Click Rate': 'Wskaźnik kliknięć',
    'Active': 'Aktywny',
    'Scheduled': 'Zaplanowany',
    'Completed': 'Ukończony',
    'Paused': 'Wstrzymany',
    'Welcome Series': 'Seria powitalna',
    'Product Launch': 'Wprowadzenie produktu',
    'Abandoned Cart': 'Porzucony koszyk',
    'Weekly Newsletter': 'Tygodniowy newsletter',
    'Modern Welcome': 'Nowoczesne powitanie',
    'Product Showcase': 'Prezentacja produktu',
    'Minimal Newsletter': 'Minimalny newsletter',
    'Flash Sale': 'Wyprzedaż błyskawiczna',
    'Onboarding': 'Wdrożenie',
    'Marketing': 'Marketing',
    'Content': 'Treść',
    'Promotional': 'Promocyjny',
    
    // Product Recommendation Demo
    'View similar': 'Zobacz podobne',
    'Add to cart': 'Dodaj do koszyka',
    'Promote Variant': 'Promuj wariant',
    'Recent Activity': 'Ostatnia aktywność',
    'Personalized for': 'Spersonalizowane dla',
    'User Context': 'Kontekst użytkownika',
    'Top Recommendations': 'Najlepsze rekomendacje',
    'Offline Metrics': 'Metryki offline',
    'Online Metrics': 'Metryki online',
    'Similar Items (Content-Based)': 'Podobne przedmioty (oparte na treści)',
    'Frequently Bought Together': 'Często kupowane razem',
    'A/B Test Results': 'Wyniki testów A/B',
    'Product Recommendation System': 'System rekomendacji produktów',
    'Hybrid (Collaborative + Content) Recommendations with Evaluation and A/B Testing': 'Hybrydowe rekomendacje (współpracujące + treść) z oceną i testami A/B',
    
    // General terms
    'Dashboard': 'Panel',
    'Overview': 'Przegląd',
    'Details': 'Szczegóły',
    'Settings': 'Ustawienia',
    'Profile': 'Profil',
    'Search': 'Szukaj',
    'Filter': 'Filtr',
    'Sort': 'Sortuj',
    'Date Range': 'Zakres dat',
    'Export': 'Eksportuj',
    'Import': 'Importuj',
    'Refresh': 'Odśwież',
    'Edit': 'Edytuj',
    'Delete': 'Usuń',
    'Add': 'Dodaj',
    'Create': 'Utwórz',
    'Update': 'Aktualizuj',
    'Remove': 'Usuń',
    'Select': 'Wybierz',
    'Choose': 'Wybierz',
    'Upload': 'Prześlij',
    'Download': 'Pobierz',
    'Print': 'Drukuj',
    'Share': 'Udostępnij',
    'Copy': 'Kopiuj',
    'Paste': 'Wklej',
    'Cut': 'Wytnij',
    'Undo': 'Cofnij',
    'Redo': 'Ponów',
    'Help': 'Pomoc',
    'About': 'O nas',
    'Contact': 'Kontakt',
    'Support': 'Wsparcie',
    'Feedback': 'Opinia',
    'Report': 'Raport',
    'Bug': 'Błąd',
    'Feature': 'Funkcja',
    'Request': 'Żądanie',
    'Issue': 'Problem',
    'Fix': 'Napraw',
    'Error': 'Błąd',
    'Warning': 'Ostrzeżenie',
    'Info': 'Informacja',
    'Success': 'Sukces',
    'Failed': 'Nieudane',
    'Pending': 'Oczekujące',
    'Processing': 'Przetwarzanie',
    'Complete': 'Kompletne',
    'Incomplete': 'Niekompletne',
    'Yes': 'Tak',
    'No': 'Nie',
    'True': 'Prawda',
    'False': 'Fałsz',
    'On': 'Włączone',
    'Off': 'Wyłączone',
    'Enabled': 'Włączone',
    'Disabled': 'Wyłączone',
  }
};

export function useAutoTranslate() {
  const { locale } = useLanguageCtx();

  const autoTranslate = (text: string): string => {
    // If English, return original text
    if (locale === 'en') return text;
    
    // Check if we have a translation for this text
    const translation = translations[locale]?.[text];
    return translation || text;
  };

  return { autoTranslate, locale };
}

export default useAutoTranslate;